#!/usr/bin/env bash

set -euo pipefail

[ "${BASH_VERSINFO:-0}" -ge 4 ] || {
  echo "bash version 4 or higher is required" >&2
  exit 1
}

root=$(git rev-parse --show-toplevel)
include=(
  "${root}"/draft/basis/bin/lib/config/*.bash
  "${root}"/draft/basis/bin/lib/main.bash
)

for script in "${include[@]}"; do
  # shellcheck source=draft/basis/bin/lib/main.bash
  source "${script}"
done
